### ISSUE TITLE
Coop conflict: ScienceVessel and Raven on Space

### ISSUE THREAD

**Issue by vadim-tivikov** [bobo38/TheCoreLite#12]
USQwerty/TheCore Lite.SC2Hotkeys

```
BuildScienceVessel/Starport=Space
Raven/Starport=Space
```

**Comment by bobo38** [comment]
Thanks for having reported this bug, I was able to reproduce it 

The solution has been to map ScienceVessel to C
– MultiPlayer Raven keeps on being on Space (priority 1)
– Coop ScienceVessel is fixed to prevent Coop player anointment due to unbound warning (priority 2)
– WoL campaign player could temporarily swap to Space if it's more convenient
