### ISSUE TITLE
What happens if you stop supporting this project?

### ISSUE THREAD

**Issue by lfaoro** [bobo38/TheCoreLite#42]
I'd like to switch to this keyset although I'm worried if supports ceases we'll end up having to switch back and rewiring our brain to the standard hotkeys

**Comment by bobo38** [comment]
This repository will still be online

Orphan or no longer supported custom hotkey setups require minor adjust patch after patch: this was the status as I started the work on TheCore Lite (no update since JaKaTaK's release on TeamLiquid). Many players still use unsupported version of TheCore and keep making them work. There is not as many changes in SC2 those days, as it have been with LoTV release, Nova mission pack, Coop commander releases. Foundations should be solid enough to go this way with limited effort

If I disappear from the web, some volunteer might fork this repository and maintain on the long run (or a group of persons, but I don't think this big of a community would be needed)

**Comment by lfaoro** [comment]
thank you @bobo38 I appreciate your effort, I will start the switch. Meanwhile if you need any help with the project, let me know -- I'm a developer.

**Comment by bobo38** [comment]
The python code to check the Seed is ugly dirty but just works. I'm waiting for significant progress on ConflictChecks.py and Defaults.ini extraction from data game harvesting automation to start making it better 

Any issue with the hotkey setup can be pointed at as a bug on this bug tracker or on Discord channel (then I can file it a bug here). As well any enhancement in user's local copy could be communicated and arbitrated for modification to be used upstream. Such example https://github.com/bobo38/TheCoreLite/issues/24 (Queen and Overlord on E)

At patch update, some users helped submitting pull request to bind new commanders. I appreciate a lot, as I'm not myself a Coop player. That's quite helpful. If I do myself, my goal is fix unbounds with something that seems to make sense but I cannot test, lack of time and interest to run commander up to level 15 for last detail optimization

Examples:
https://github.com/bobo38/TheCoreLite/pull/40 (Stettman)
https://github.com/bobo38/TheCoreLite/pull/41 (Mengsk)
=> best pull-request would be done on US QWERTY or in TheCore Lite.SC2Hotkeys seed at root of the repository to avoid the pain of keyboard layout translation (last time it was not too painful to convert from French AZERTY to US QWERTY manually, so that there is no real need for automation there)

**Comment by lfaoro** [comment]
Maybe we can drop support for other layouts? It's just easier to switch your system keyboard layout to US when you play starcraft rather than us supporting a dozen layouts which are already system supported anyway.

**Comment by lfaoro** [comment]
What is exactly the Seed check? I can reimplement the tools you need, although I need a full description of what these tools have to do and which data they need to manipulate.

We can have a chat where I take notes.

**Comment by bobo38** [comment]
Converting to other keyboard layouts is the easy part ;-) The one which works and was primary purpose in original repository

All the logs .log at root of project are checks' logs, some are from beginning of TheCore: output and code are dirty but just works. I can support new SC2 content in 1-2 hours and spot regression that cannot be found easily within GUI.

If you're interested in supporting SC2 community with your coding skills you can join here and see discussions
https://discord.gg/qseNPub
